hotdeal/urls.py
from django.contrib import admin
from django.urls import path, include
from hotdealapp import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('hotdealapp/', include('hotdealapp.urls'),)
]

hotdealapp/urls.py
from django.urls import path
from . import views


app_name = 'hotdeal'

urlpatterns = [
    path('', views.index, name="index"),
    path('result/', views.result, name="result"),
]

hotdealapp/models.py
from django.db import models

# Create your models here.
class Hotdeal(models.Model):
    key = models.CharField(max_length=100)
    target = models.IntegerField(choices=((1, "제목 + 내용"), (2, "제목")), default=1)
    cnt = models.IntegerField(default=1)

    # @property
    # def update_count(self):
    #     self.count = self.count+1
    #     return self.count

hotdealapp/forms.py
from django import forms
from .models import Hotdeal

# Choice = ((1, "제목 + 내용"), (2, "제목"))

class HotdealForm(forms.ModelForm):
    
    key = forms.CharField(
        label="",
        required=True,
        widget=forms.TextInput(attrs={'name': 'key', 'placeholder': '상품 입력', 'class': 'search_input', 'autocomplete': 'off'}),
    )
    # target = forms.ChoiceField(
    #     label="",
    #     choices=Choice)
    class Meta:
        model = Hotdeal
        fields = ['key']

    # def save(self):
    #     hotdeal = Hotdeal.objects.get(key=self.key)
    #     if hotdeal:
    #         hotdeal.count += 1
    #     else:
    #         hotdeal = super().save()
    #     return hotdeal
            

hotdealapp/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist

from .forms import HotdealForm
from .models import Hotdeal
from .data import get_fmk, get_ppmp, get_ruliweb

def get_rank():
    rank_limit = 5
    search_rank = []
    for rank in Hotdeal.objects.values('key').order_by('-count', 'key').annotate(count=Count('key'))[:rank_limit]:
        search_rank.append((rank.get('count'), rank.get('key')))
    return search_rank

def index(request):
    form = HotdealForm()
    context = {
        'form': form,
    }
    return render(request, 'hotdealapp/index.html', context)



def result(request):
    key = request.GET.get('key')
    try:
        hotdeal  = Hotdeal.objects.get(key=key)
        hotdeal.cnt += 1
        hotdeal.save()
    except ObjectDoesNotExist:
        Hotdeal.objects.create(key=key)
    # ranks = get_rank()
    ranks = Hotdeal.objects.order_by('-cnt')
    result = []
    result += get_fmk(key=key)
    # result += get_ppmp(key=key)
    result += get_ruliweb(key=key)
    context = {
        'key': key,
        'results': sorted(result, key=lambda x: (-len(x['date']), x['date']), reverse=True),
        'ranks': ranks,
    }
    return render(request, 'hotdealapp/result.html', context)

hotdealapp/templates/hotdealapp/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
    .logo {
        width: 300px;
    }

    .icon {
        border-radius: 20px;
        border: 2px solid #343d46;
        margin: 0 30px;
        width: 70px;
        height: 70px;
    }
</style>

{% endblock %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center"
    style="margin-top: 30px; margin-bottom:30px; min-height: 100vh;">
    <div class="d-flex flex-column align-items-center">
        <img class="logo" src="{%static 'images/hotsearch.png' %}" alt="Hotdeal">
        <form action="{% url 'hotdeal:result' %}" method="GET"
            class="d-flex flex-column justify-content-center align-items-center mt-4 mb-5">
            <div class="container h-100">
                <div class="d-flex justify-content-center h-100">
                    <div class="searchbar d-flex justify-content-between align-items-center">
                        <button class="bg-transparent border-0">
                            <div class="search_icon text-white text-decoration-none"><i class="fas fa-search"></i></div>
                        </button>
                        <label for="key"></label><input type="text" id="key" name="key" class="search_input" autocomplete="off">
                    </div>
                </div>
            </div>
        </form>
        <div>
            <a style="text-decoration: none;" href="https://www.fmkorea.com/hotdeal" target="_blank"
                rel="noopener noreferrer">
                <img class="icon" src="{% static 'images/fm.png' %}" alt="fmkorea">
            </a>
            <a style="text-decoration: none;" href="https://bbs.ruliweb.com/market/board/1020" target="_blank"
                rel="noopener noreferrer">
                <img class="icon" src="{% static 'images/ruli.png' %}" alt="ruliweb">
            </a>
            <a style="text-decoration: none;" href="http://www.ppomppu.co.kr/zboard/zboard.php?id=ppomppu"
                target="_blank" rel="noopener noreferrer">
                <img class="icon" src="{% static 'images/ppomppu.png' %}" alt="ppomppu">
            </a>
        </div>
    </div>
</div>
{% endblock %}

hotdealapp/templates/hotdealapp/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<nav class="navbar navbar-expand-md navbar-dark d-flex justify-content-center mt-4"
    style="height: 70px; padding: 0 380px;">
    <div class="container d-flex justify-content-center">
        <form action="" method="GET" class="d-flex flex-column justify-content-center align-items-center">
            <div class="container h-100 d-flex justify-content-center align-items-center">
                <div class="d-flex justify-content-center h-100">
                    <div class="searchbar d-flex justify-content-between align-items-center">
                        <button class="bg-transparent border-0">
                            <div class="search_icon text-white text-decoration-none"><i class="fas fa-search"></i></div>
                        </button>
                        <label for="key"></label><input type="text" id="key" name="key" class="search_input"
                            autocomplete="off" value="{{ key }}">
                    </div>
                </div>
            </div>
        </form>
    </div>
</nav>
<div class="row mt-3">
    <section class="w3-margin-top col-2 ml-5">
        <ul class="list-group d-flex justify-content-center">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="text-center">순위</span>
                <span class="text-center">이름</span>
                <span class="text-center">검색수</span>
            </li>
            {% for rank in ranks %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="badge badge-pill badge-info mr-1 text-center">{{ forloop.counter }}</span>
                <form action="{% url 'hotdeal:result' %}"><input type="text" hidden value="{{ rank.1 }}"
                        name="key"><span class="text-center"><button
                            class="bg-transparent w3-border-0">{{ rank.key }}</button></span></form>
                <span class="badge badge-primary badge-pill ml-1 text-center">{{ rank.cnt }}</span>
            </li>
            {% endfor %}
        </ul>
    </section>

    <section class="w3-margin-top col-9">
        <div class="container">
            <table class="w3-table-all w3-hoverable" id="result">
                <thead>
                    <tr class="w3-light-grey">
                        <th></th>
                        <th class="w3-center">제목</th>
                        <th class="w3-center">시간</th>
                    </tr>
                </thead>
                {% for result in results %}
                <tr>
                    <td><a href="{{ result.link }}" target="_blank">
                            {% if result.img == None %}
                            <img src="{% static 'images/no_img_64.png' %}" alt="">
                            {% else %}
                            <img src="{{ result.img }}" alt="">
                            {% endif %}
                        </a>
                    </td>
                    <td><a href="{{ result.link }}" target="_blank">{{ result.title }}</a></td>
                    <td class="w3-center">{{ result.date }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td></td>
                    <td>
                        <h1 class="w3-center">정보가 없습니다.</h1>
                    </td>
                    <td></td>
                </tr>
                {% endfor %}
            </table>

        </div>
    </section>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HotDeal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
        integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">
    {% block css %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>